### PR TITLE
ci: replace travis with github actions

### PR DESCRIPTION
**Pull request by curbengh**

### CODE REVIEW

**Comment by curbengh** [comment]
@YoshinoriN github actions not enabled for this repo yet?

**Comment by YoshinoriN** [comment]
> @YoshinoriN github actions not enabled for this repo?

No. It is enabled.
It seems same with https://github.com/hexojs/hexo.  🤔

**Comment by YoshinoriN** [comment]
@segayuu 
We adding GitHubAction to this repo. 

The settings seem the same with https://github.com/hexojs/hexo
But, not triggered.

You added GitHubAction to hexo repo. Do you come up with what is a problem?

> https://github.com/hexojs/hexo/pull/4169

**Comment by curbengh** [comment]
@YoshinoriN 
It's triggered now after I push to upstream [branch](https://github.com/hexojs/hexo-migrator-wordpress/tree/gh-action).

**Pull request merged**
